# Generated by Django 4.2.5 on 2023-09-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blogsettings_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsettings',
            name='analytics_code',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='blogsettings',
            name='beian_code',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='blogsettings',
            name='comment_need_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blogsettings',
            name='global_footer',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='blogsettings',
            name='global_header',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='blogsettings',
            name='gongan_beiancode',
            field=models.TextField(blank=True, default='', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='blogsettings',
            name='show_gongan_code',
            field=models.BooleanField(default=False),
        ),
    ]
